### ISSUE TITLE
Using npm start, localhost:3000 doesn't work

### ISSUE THREAD

**Issue by shambhusharma** [barryels/realworld-mithril#36]
I've installed Node.js -v 6.10.2 and npm -v 3.10.10

And I've used following steps to install:
1. git clone https://github.com/barryels/realworld-mithril.git
2. cd realworld-mithril
3. npm install
4. npm start

Step 4 doesn't show any error, but http://localhost:3000 doesn't work!

When searching for any solutions for this, I found the following command, using which the application shows up in browser:
`node ./node_modules/http-server/bin/http-server public -p 3000 -s`
But I'm not sure if this is the proper approach to this.

I'm very much new to Mithril or any JS Framework, So I really appreciate any help in getting started here. Thanks

**Comment by barryels** [comment]
Thanks for the feedback... What OS are you using?

Also, are you saying that:
`node ./node_modules/http-server/bin/http-server public -p 3000 -s`
works?

**Comment by shambhusharma** [comment]
I'm using Windows 10.

And yes, it works with that command, but the page shows as 'Loading...' for Feeds list, Tags list etc.

**Comment by barryels** [comment]
Cool, I'll update the run script to include `node ./node_modules....` seems to be a Windows specific issue.

The 'Loading...' is because it seems the demo API is down
go here: http://conduit.productionready.io/api/tags

**Comment by shambhusharma** [comment]
@barryels Thanks for the update. Now`npm run ui-server` works, but `npm start` still doesn't start the server.

It worked for me after changing the script to run both of them in parallel (by replacing `&` with `|` ), as:
`"dev": "npm run ui-build-js-watch | npm run ui-server"`

But looks like this syntax is platform specific, as mentioned in an answer at stackoverflow [here](http://stackoverflow.com/questions/30950032/how-can-i-run-multiple-npm-scripts-in-parallel/35455532#35455532). And as a solution `npm-run-all` module is suggested.

I'll try this approach tomorrow and update here if that works on both Windows and Ubuntu. Thanks

**Comment by barryels** [comment]
@shambhusharma please test and let me know if this fixes the issue... You'll need to run `npm install` first to install the new npm-run-all dep, then `npm start`

**Comment by shambhusharma** [comment]
@barryels Sorry for the delay in replying to this.

I've tested it locally and it is working properly now. Thanks a lot.

**Comment by barryels** [comment]
Glad to hear it :smile:
